In [ ]:
"""
Task 1 - Write a program that allows you to enter 4 numbers and store them in a file called numbers
"""
MaxNum = 4                              #Specify numbers to ask
x = [0] * MaxNum                        #Assign array
for y in range(MaxNum):                 #Iterate as needed
    x[y] = input("Specify a number")    #Collect input in array

#print (x)    

Task1_File = open("Week4Task1_Store4Numbers.txt","w") #Create txt file
Task1_File.write(str(x))                                #Write array from input gathering
Task1_File.close()                                      #Close file

In [ ]:
"""
Task 2 - Write a program to ask a student for their percentage mark and convert this to a grade. The conversion will be done in a function called mark_grade
Extension to task 2
Ask the user for their target grade and print this with their mark
If their target grade > exam grade display a suitablemessage
If their target grade = exam grade display a suitablemessage
If their target grade < exam grade display a suitablemessage
"""

#Convert percentage to grade
def mark_grade(Score):
    if Score >= 90 and Score <= 100:
        GradeAchieved = "A*" 
    elif Score >= 80 and Score < 90:
            GradeAchieved = "A"
    elif Score >= 70 and Score < 80:
            GradeAchieved = "B"
    elif Score >= 60 and Score < 70:
            GradeAchieved = "C"
    elif Score >= 50 and Score < 60:
            GradeAchieved = "D"
    elif Score >= 0 and Score < 50:
            GradeAchieved = "Fail"
    return GradeAchieved            

ScoreX = int(input("What score did you get in the test? 0-100"))    #Gather percentage score
TargetGrade = input("Which grade were you aiming for?")             #Gather target grade
ExamGrade = mark_grade(ScoreX)                                      #Convert score to grade
GradeList = ["Fail","D","C","B","A","A*"]                           #Define list of grades for indexing
ExamGradeInd = GradeList.index(ExamGrade)                           #Get index position of grade
TargetGradeInd = GradeList.index(TargetGrade)                       #Get index position of target grade
#print(ExamGradeInd, TargetGradeInd)

if TargetGradeInd > ExamGradeInd:
    print("Unfortunately a score of", ScoreX, "equates to the grade", ExamGrade, "which is below your target of", TargetGrade)
if TargetGradeInd == ExamGradeInd:
    print("Well done, you've score", ScoreX, "which equates to the grade", ExamGrade, ", just as you were aiming for.")
if TargetGradeInd < ExamGradeInd:
    print("Congratulations, your score of", ScoreX, "equates to the grade", ExamGrade, "which is above your target of", TargetGrade)                                                 

In [57]:
"""
Task 3 
1. Create a 1D array of numbers from 0 to 9
2. Create a 3×3 NumPy array of all Boolean value Trues
3. Extract all odd numbers from array of 1 10
4. Replace all odd numbers in an array of 1 10 with the value 1
5. Convert a 1D array to a 2D array with 2 rows
6. Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals 
Extension
7. Create the following pattern without hardcoding. Use only NumPy functions
8. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) remove all repeating items present in array b
9. Get all items between 3 and 7 from a and b and sum them together
"""

import numpy as np
#1. Create a 1D array of numbers from 0 to 9
array = np.arange(10)
print ("1:", array) 

#2. Create a 3×3 NumPy array of all Boolean value Trues
array2 = np.ones((3,3))
print("2:", array2)

#3. Extract all odd numbers from array of 1 10
array3 = np.arange(2,11,2)
print("3:", array3)

#4. Replace all odd numbers in an array of 1 10 with the value 1
array4 = np.arange(1,11,1)
array4[array4%2==1] = 1
print("4:", array4)

#5. Convert a 1D array to a 2D array with 2 rows
array5 = np.arange(0,10,1).reshape(2,5)
print("5:", array5)

#6. Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals 
a = np.arange(1,10,1).reshape(3,3)
b = np.arange(10,19,1).reshape(3,3)
c = np.dot(a,b)
d = sum(a,b)
#print("6:", a)
#print("6:", b)
print("6:", c)
print("6:", d)

#I'm assuming that 'stack these two arrays vertically' meant stack/reshape each of them first into a 2d array before doing dot / sum?




#Extension
#7. Create the following pattern without hardcoding. Use only NumPy functions - [1,1,1 2,2,2 3,3,3 1,2,3 1,2,3 1,2,3]

#Set input variables to make the start and end values dynamic
Start = 1                           
End = 3    

a = np.arange(Start,End+Start)          #Create inital array of Start to End in sequential order
b = np.repeat(a,End)                    #Create array of repeating elements of the original array
c = np.tile(a,End)                      #Create array of repeating pattern of original array
d = np.concatenate((b,c),axis=None)     #Combine the arrays as 1d array

#print("a",a)
#print("b",b)
#print("c",c)
print("7.d", d)



#8. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) remove all repeating items present in array b

#Assuming this means to return only the non-repeated items from array b.
#store each array into a set: a, b
a = [1,2,3,4,5]
b = [4,5,6,7,8,9]
#using the lists as Sets, subtract the 1st set from the 2nd set leaving just the non-overlapping values from 2nd list. Then return to original format, a sorter list.
OutPut = list(sorted(set(b)-set(a))) print("8",OutPut)



#9. Get all items between 3 and 7 from a and b and sum them together: a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9)

a = [1,2,3,4,5]
b = [4,5,6,7,8,9]
#Assuming lists are sequential

#Define the start and end list items to look for
Start = 3
End = 7
#Find the index position of start and end item with a failsafe being the first or last index position in the list size
if Start not in a:
    aStart = 0
else: aStart = a.index(Start) 
if End not in a:
    aEnd = len(a)-1
else: aEnd = a.index(End) 
#Find the position of start and end with a failsafe being the first or last position in the list size
if Start not in b:
    bStart = 0
else: bStart = b.index(Start) 
if End not in b:
    bEnd = len(b)-1
else: bEnd = b.index(End) 
#print(aStart,aEnd, bStart,bEnd)

#Slice each array using start and end positions then sum
aX = a[aStart:aEnd]
bX = b[bStart:bEnd]
#print(aX,bX)
cX = np.concatenate((aX,bX))
d = np.sum(cX)
print("9:",d)

1: [0 1 2 3 4 5 6 7 8 9]
2: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3: [ 2  4  6  8 10]
4: [ 1  2  1  4  1  6  1  8  1 10]
5: [[0 1 2 3 4]
 [5 6 7 8 9]]
6: [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
6: [[22 26 30]
 [25 29 33]
 [28 32 36]]
7.d [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
8 [6, 7, 8, 9]
9: 22


22
